version: 2.1

commands:
  cc-download-binary:
    description: "Code Climate Download Binary"
    steps:
      - run:
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

  cc-before-build:
    description: "Code Climate before-build"
    steps:
      - run: "./cc-test-reporter before-build"

  all-tests:
    description: "Roda todos os testes do projeto (unitários e integração)"
    steps:
      - run: "pipenv run test"

jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install pip/pipenv
          command: pip install --user -U pip==19.3.1 pipenv==2018.11.26
      - run:
          name: Install Pipfile.lock
          command: pipenv install --deploy --ignore-pipfile --dev
      - run:
          name: Install project in dev-mode
          command: pipenv run pip install -e .
      - cc-download-binary
      - cc-before-build
      - all-tests
      - run:
          when: on_success
          command: "./cc-test-reporter after-build --coverage-input-type coverage.py"
workflows:
  version: 2
  test:
    jobs:
      - test
